### ISSUE TITLE
When enable this plugin，New post on discussion always be merged to exist adjacency post (2 posts are all send by me)

### ISSUE THREAD

**Issue by nathanli97** [FriendsOfFlarum/filter#11]
Flarum Version：

0.1.0-beta.8

Installed plugins：
        "antoinefr/flarum-ext-money": "^0.8.0",(Installed,But Not enabled)
        "antoinefr/flarum-ext-online": "^0.4.0",(Installed,But Not enabled)
        "clarkwinkelmann/flarum-ext-author-change": "^0.2.0",
        "clarkwinkelmann/flarum-ext-circle-groups": "^0.2.1",
        "clarkwinkelmann/flarum-ext-comicsans": "^0.2.0",
        "clarkwinkelmann/flarum-ext-emojionearea": "^0.2.2",
        "clarkwinkelmann/flarum-ext-post-date": "^0.1.1",
        "clarkwinkelmann/flarum-ext-status": "^0.1.1",
        "csineneo/lang-simplified-chinese": "^1.13",(Installed,But Not enabled)
        "datitisev/flarum-ext-dashboard": "v0.1.0-beta.8.2",
        "extum/flarum-ext-material": "^1.0@beta",(Installed,But Not enabled)
        "flagrow/ads": "^0.2.4",
        "flame05/flarum-ita": "^1.1",(Installed,But Not enabled)
        "flarum/approval": "^0.1.0",
        "flarum/auth-facebook": "^0.1.0",(Installed,But Not enabled)
        "flarum/auth-github": "^0.1.0",
        "flarum/auth-twitter": "^0.1.0",(Installed,But Not enabled)
        "flarum/bbcode": "^0.1.0",
        "flarum/core": "^0.1.0",
        "flarum/emoji": "^0.1.0",
        "flarum/flags": "^0.1.0",
        "flarum/lang-english": "^0.1.0",
        "flarum/likes": "^0.1.0",
        "flarum/lock": "^0.1.0",
        "flarum/markdown": "^0.1.0",
        "flarum/mentions": "^0.1.0",
        "flarum/pusher": "^0.1.0",(Installed,But Not enabled)
        "flarum/statistics": "^0.1.0",
        "flarum/sticky": "^0.1.0",
        "flarum/subscriptions": "^0.1.0",
        "flarum/suspend": "^0.1.0",(Installed,But Not enabled)
        "flarum/tags": "^0.1.0",
        "flarumalshain/showlastpost": "^1.2",
        "fof/best-answer": "^0.1.11",
        "fof/byobu": "*",
        "fof/default-user-preferences": "^0.2.0",
        "fof/drafts": "^0.1.12",
        "fof/filter": "^0.1.0@beta",
        "fof/follow-tags": "^0.4.2",
        "fof/formatting": "^0.1.5",
        "fof/forum-statistics-widget": "^0.2.0",
        "fof/frontpage": "^0.1.3",
        "fof/gamification": "^0.1.9",(Installed,But Not enabled)
        "fof/linguist": "^0.4.2",
        "fof/links": "^0.3.0",
        "fof/merge-discussions": "^0.3.3",
        "fof/nightmode": "^0.4.0",
        "fof/polls": "^0.1.2",
        "fof/prevent-necrobumping": "^0.2.1",
        "fof/profile-image-crop": "^0.1.2",
        "fof/reactions": "^0.3.4",
        "fof/sitemap": "^0.5.1",
        "fof/socialprofile": "^0.1.2",
        "fof/spamblock": "^0.2.2",
        "fof/split": "*",
        "fof/subscribed": "*",
        "fof/upload": "^0.9.2",
        "fof/user-bio": "^0.2.0",
        "fof/user-directory": "^0.3.4",
        "fof/username-request": "^0.2.0",(Installed,But Not enabled)
        "irony/flarum-ext-login2see": "^0.0.1",
        "itnt/flarum-backtop": "v0.1.7.2",
        "jslirola/flarum-ext-login2seeplus": "^0.1.5",(Installed,But Not enabled)
        "jsthon/flarum-ext-simplified-chinese": "^0.1.0@beta",(Installed,But Not enabled)
        "kvothe/reply-to-see": "^0.1.2",
        "kvothe/signup-button": "^0.1.4",
        "lcinhk/flarum-ext-acgembed": "^0.5.2",
        "littlegolden/flarum-lang-simplified-chinese": "^0.1.67",
        "michaelbelgium/flarum-discussion-views": "^4.0",(Installed,But Not enabled)
        "michaelbelgium/flarum-profile-views": "^3.1",
        "michaelbelgium/mybb-to-flarum": "^5.1",(Installed,But Not enabled)
        "minr/flarum-ext-auth-qq": "^0.1.6",(Installed,But Not enabled)
        "oe800/flarum-ext-bbcode-alerts": "^0.2.0",
        "reflar/cookie-consent": "^0.2.0",(Installed,But Not enabled)
        "reflar/doorman": "^0.1.6",
        "reflar/level-ranks": "^1.2",
        "s9e/text-formatter": "^2.7",
        "saleksin/flarum-auth-google": "v0.1.0-beta.8.0.3",
        "squeevee/flarum-ext-fancybox": "^0.2.0@beta",
        "the-turk/flarum-password-strength": "^0.1.3",
        "the-turk/flarum-stargazing-theme": "^0.1.1",(Installed,But Not enabled)
        "therealsujitk/flarum-ext-show-password": "^1.0",
        "v17development/flarum-seo": "^1.2"

**Comment by nathanli97** [comment]
![image](https://user-images.githubusercontent.com/52489887/88615554-c5dd3f00-d0c4-11ea-9a8b-b3fb4de01763.png)
![image](https://user-images.githubusercontent.com/52489887/88615585-d392c480-d0c4-11ea-9580-e8042378a826.png)

**Comment by Kakifrucht** [comment]
I fixed this a while ago in #9.
