### ISSUE TITLE
Permission to bypass filters

### ISSUE THREAD

**Issue by rafaucau** [FriendsOfFlarum/filter#24]
## Feature Request
It would be nice to be able to have admin posts not be added for approval when they use filtered strings.

- Add permissions for groups that can bypass string filters
- When a group has these permissions, their post will not be filtered

**Comment by imorland** [comment]
Yes I agree with you. I'll add this soon, or feel free to submit a PR if you get there before me!

**Comment by imorland** [comment]
Will be included in the upcoming `1.0.2` release :)
