### ISSUE TITLE
Posting does not work if there are a lot of bad words added in the extension settings

### ISSUE THREAD

**Issue by rafaucau** [FriendsOfFlarum/filter#28]
## Bug Report

**Current Behavior**
If I add a very large number of words to filter, writing posts does not work at all.
```
preg_replace_callback(): Empty regular expression in <b>vendor\fof\filter\src\Listener\CheckPost.php</b> on line <b>85</b><br />
```

**Steps to Reproduce**
1. Add very large number of words to filter.
2. Try writing a post that doesn't contain a single one of these words.

**Screenshots**
![image](https://user-images.githubusercontent.com/25438601/123564141-7a418280-d7b8-11eb-8446-c5c93c77edb8.png)
![image](https://user-images.githubusercontent.com/25438601/123564077-3d758b80-d7b8-11eb-8dde-3da683600841.png)

**Environment**
- Flarum version: 1.03
- Extension version: 1.0.1
- Webserver: apache, litepseed
- Hosting environment: local, shared
- PHP version: 7.4, 8.0

**Comment by datitisev** [comment]
Is this still an issue?

**Comment by rafaucau** [comment]
> @datitisev Is this still an issue?

https://user-images.githubusercontent.com/25438601/149270702-e585440f-5876-4aae-b10d-f2270783505c.mp4

**Comment by datitisev** [comment]
I'm assuming that array/regex is getting truncated because it's too big. Solution is probs to build it after a post but then that's wasting a lot of time creating a regex on every post save... 🤔 not sure what the best solution is.

**Comment by rafaucau** [comment]
If you would like to test, here is the list of words I use: [polish_bad_words.txt](https://github.com/FriendsOfFlarum/filter/files/7873888/polish_bad_words.txt)

**Comment by datitisev** [comment]
> Maybe a separate table where each word would be on a separate row? In one column the word, in the second column the generated regular expressions.

I don't think this would solve much... this would be a large query on every post save, probably taking up more time than simply generating the regex on post save from the word list 🤔.

Large query as you'd be retrieving hundreds of rows at once, I assume not a good idea.

**Comment by DavideIadeluca** [comment]
@rafaucau Should be resolved with https://github.com/FriendsOfFlarum/filter/pull/53.
