### ISSUE TITLE
Filter isn't working.

### ISSUE THREAD

**Issue by shydert** [FriendsOfFlarum/filter#31]
## Bug Report

**Current Behavior**
Well, the extension doesn't work anymore after the version 1.0.2. It doesn't put posts with the filtered words to under review.

**Steps to Reproduce**
1. Post something with a blacklisted word, then the extension will not do anything

**Comment by jobber2955** [comment]
same here, using Flarum 1.0.4
rules include english and chinese
when start a discussion, a error modal will show up and display "someting went wrong" with red background.BUT the discussion still sucessfully created and can be seen by anyone

**Comment by imorland** [comment]
@shydert @jobber2955 when you upgraded to `1.0.2` did you run any outstanding migrations as per the [release announcement](https://discuss.flarum.org/d/5131-friendsofflarum-filter/212)

This version changes the format of the stored rules, using the extension without migrating the data will result in errors/unexpected behaviour

**Comment by shydert** [comment]
Well, I'm using FreeFlarum, so I can't tell you at all, but still it won't work.

**Comment by imorland** [comment]
> Well, I'm using FreeFlarum

Ok, in that case, please try disabling the extesion, then re-enabling it. This will also trigger the extension's migration to run

**Comment by shydert** [comment]
It worked! Somehow disabling and enabling the extension worked.

**Comment by shydert** [comment]
.-.

**Comment by giobifo** [comment]
Hi @shydert, if you want resolve the problem (only for now), go to the path of your forum and open the following folders: "vendor\fof\filter\src\Listener\" and open, with Notepad++, this file: "AddCensorChecks.php".

In the line 20, replace the `PHP_EOL` character with `"\n"` (see image below).

![edit file](https://user-images.githubusercontent.com/80928012/141689917-9eb550e5-9b8e-4c13-ae5b-636c7644a27b.png)

After that, try again to create the bad words from the extension in the blog settings.

By doing this I solved the problem.

**Comment by HN-PRO** [comment]
> Hi @shydert, if you want resolve the problem (only for now), go to the path of your forum and open the following folders: `vendor\fof\filter\src\Listener\` and open, with Notepad++, this file: `AddCensorChecks.php`.
> 
> In the line 20, replace the `PHP_EOL` character with `"\n"` (see image below).
> 
> ![edit file](https://user-images.githubusercontent.com/80928012/141689917-9eb550e5-9b8e-4c13-ae5b-636c7644a27b.png)
> 
> After that, try again to create the bad words from the extension in the blog settings.
> 
> By doing this I solved the problem.



> Hi @shydert, if you want resolve the problem (only for now), go to the path of your forum and open the following folders: `vendor\fof\filter\src\Listener\` and open, with Notepad++, this file: `AddCensorChecks.php`.
> 
> In the line 20, replace the `PHP_EOL` character with `"\n"` (see image below).
> 
> ![edit file](https://user-images.githubusercontent.com/80928012/141689917-9eb550e5-9b8e-4c13-ae5b-636c7644a27b.png)
> 
> After that, try again to create the bad words from the extension in the blog settings.
> 
> By doing this I solved the problem.

great！it's work for me. @giobifo
