### ISSUE TITLE
Delete discussion instead of flagging post

### ISSUE THREAD

**Issue by dexif** [FriendsOfFlarum/filter#42]
## Feature Request

**Is your feature request related to a problem? Please describe.**

We have a lot of spammers on our forum every day who constantly write the same messages and they have to be deleted. We need to prevent spammers from creating discussions instead of just flagging them.
https://discuss.flarum.org/d/32611-how-to-stop-chinese-spam

**Describe the solution you'd like**

Just a toggle in the admin panel to enable this behavior

**Comment by imorland** [comment]
Implemented in #43
